export const allStoryboards = [
	{
		id: 1,
		type: 'Storyboard',
		title: 'Trial: Current Social Dining Experience',
		robot: false,
		scenes: [
			{ id: 1, title: 'Describe Scenario' },
			{ id: 2, title: 'Seating + Ordering' },
			{ id: 3, title: 'Eating/Drinking' },
		],
	},
	{
		id: 2,
		type: 'Storyboard',
		title: 'At Family-style restaurant, with a 5 friends/family',
		robot: true,
		scenes: [
			{ id: 1, title: 'Greeting' },
			{ id: 2, title: 'Seating' },
			{ id: 3, title: 'Menus + Ordering' },
			{ id: 4, title: 'Eating/Drinking' },
			{ id: 5, title: 'Eating/Drinking' },
			{ id: 6, title: 'Payment + Leaving' },
		],
	},
	{
		id: 3,
		type: 'Moments',
		title: 'Eating/Drinking Experience @ Family-style restaurant, with 5 friends/family',
		robot: true,
		scenes: [
			{ id: 1, title: 'Waiting for food' },
			{ id: 2, title: 'Serving food' },
			{ id: 3, title: 'Eating' },
			{ id: 4, title: 'Passing objects' },
			{ id: 5, title: 'Sharing food' },
			{ id: 6, title: 'Talking' },
			{ id: 7, title: 'Listening' },
			{ id: 8, title: 'Learn about you' },
		],
	},
	{
		id: 4,
		type: 'Storyboard',
		title: 'At Fine-dining restaurant, with a date',
		robot: true,
		scenes: [
			{ id: 1, title: 'Greeting' },
			{ id: 2, title: 'Seating' },
			{ id: 3, title: 'Menus + Ordering' },
			{ id: 4, title: 'Eating/Drinking' },
			{ id: 5, title: 'Eating/Drinking' },
			{ id: 6, title: 'Payment + Leaving' },
		],
	},
	{
		id: 5,
		type: 'Moments',
		title: 'Eating/Drinking Experience @ Fine-dining restaurant, with a date',
		robot: true,
		scenes: [
			{ id: 1, title: 'Waiting for food' },
			{ id: 2, title: 'Serving food' },
			{ id: 3, title: 'Eating' },
			{ id: 4, title: 'Romantic Gestures' },
			{ id: 5, title: 'Sharing food' },
			{ id: 6, title: 'Talking' },
			{ id: 7, title: 'Listening' },
			{ id: 8, title: 'Learn about you' },
		],
	},
]

// export const allStoryboards = [
// 	{
// 		id: 1,
// 		title: 'Trial Storyboard: Describe current setting',
// 		scenes: [
// 			{ id: 1, title: 'Getting here' },
// 			{ id: 2, title: 'Present scenario' },
// 			{ id: 3, title: 'After study plans' },
// 		],
// 	},
// 	{
// 		id: 2,
// 		title: 'Current Experience: At a restaurant, with a group of people',
// 		scenes: [
// 			{ id: 1, title: 'Greeting' },
// 			{ id: 2, title: 'Seating' },
// 			{ id: 3, title: 'Menus + Ordering' },
// 			{ id: 4, title: 'Eating/Drinking' },
// 			{ id: 5, title: 'Eating/Drinking' },
// 			{ id: 6, title: 'Payment' },
// 		],
// 	},
// 	{
// 		id: 3,
// 		title: 'Current Experience: Family-style restaurant, with 5 friends/family',
// 		scenes: [
// 			{ id: 1, title: 'Waiting for food' },
// 			{ id: 2, title: 'Serving food' },
// 			{ id: 3, title: 'Eating' },
// 			{ id: 4, title: 'Passing objects' },
// 			{ id: 5, title: 'Sharing food' },
// 			{ id: 6, title: 'Talking' },
// 			{ id: 7, title: 'Listening' },
// 			{ id: 8, title: 'Learn about you' },
// 		],
// 	},
// 	{
// 		id: 4,
// 		title: 'Current Experience: Fine-Dining restaurant, with a date',
// 		scenes: [
// 			{ id: 1, title: 'Waiting for food' },
// 			{ id: 2, title: 'Serving food' },
// 			{ id: 3, title: 'Eating' },
// 			{ id: 4, title: 'Romantic gestures' },
// 			{ id: 5, title: 'Sharing food' },
// 			{ id: 6, title: 'Talking' },
// 			{ id: 7, title: 'Listening' },
// 			{ id: 8, title: 'Learn about you' },
// 		],
// 	},
// 	{
// 		id: 5,
// 		title: 'Current Experience: Your Choice restaurant, with a Your Choice group',
// 		scenes: [
// 			{ id: 1, title: 'Waiting for food' },
// 			{ id: 2, title: 'Serving food' },
// 			{ id: 3, title: 'Eating' },
// 			{ id: 4, title: 'Learn about you' },
// 			{ id: 5, title: 'Talking' },
// 			{ id: 6, title: 'Listening' },
// 			{ id: 7, title: 'Your Choice!' },
// 			{ id: 8, title: 'Your Choice!' },
// 		],
// 	},
// 	{
// 		id: 6,
// 		title: 'Expected Experience: At a restaurant, with a group of people',
// 		scenes: [
// 			{ id: 1, title: 'Greeting' },
// 			{ id: 2, title: 'Seating' },
// 			{ id: 3, title: 'Menus + Ordering' },
// 			{ id: 4, title: 'Eating/Drinking' },
// 			{ id: 5, title: 'Eating/Drinking' },
// 			{ id: 6, title: 'Payment' },
// 		],
// 	},
// 	{
// 		id: 7,
// 		title: 'Expected Experience: Family-style restaurant, with 5 friends/family',
// 		scenes: [
// 			{ id: 1, title: 'Waiting for food' },
// 			{ id: 2, title: 'Serving food' },
// 			{ id: 3, title: 'Eating' },
// 			{ id: 4, title: 'Passing objects' },
// 			{ id: 5, title: 'Sharing food' },
// 			{ id: 6, title: 'Talking' },
// 			{ id: 7, title: 'Listening' },
// 			{ id: 8, title: 'Learn about you' },
// 		],
// 	},
// 	{
// 		id: 8,
// 		title: 'Expected Experience: Fine-Dining restaurant, with a date',
// 		scenes: [
// 			{ id: 1, title: 'Waiting for food' },
// 			{ id: 2, title: 'Serving food' },
// 			{ id: 3, title: 'Eating' },
// 			{ id: 4, title: 'Romantic gestures' },
// 			{ id: 5, title: 'Sharing food' },
// 			{ id: 6, title: 'Talking' },
// 			{ id: 7, title: 'Listening' },
// 			{ id: 8, title: 'Learn about you' },
// 		],
// 	},
// 	{
// 		id: 9,
// 		title: 'Expected Experience: Your Choice restaurant, with a Your Choice group',
// 		scenes: [
// 			{ id: 1, title: 'Waiting for food' },
// 			{ id: 2, title: 'Serving food' },
// 			{ id: 3, title: 'Eating' },
// 			{ id: 4, title: 'Learn about you' },
// 			{ id: 5, title: 'Talking' },
// 			{ id: 6, title: 'Listening' },
// 			{ id: 7, title: 'Your Choice!' },
// 			{ id: 8, title: 'Your Choice!' },
// 		],
// 	},
// ]
